### ISSUE TITLE
Unable to install ‘Ver-ID-Credentials-Cordova-Plugin’ for ionic Cordova platform Android

### ISSUE THREAD

**Issue by sanidkpc** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#5]
After cloning the plugin repo to a local directory, I ran
`cordova plugin add <path to the plugin>`
but I am getting the error below:
```
Error during processing of action! Attempting to revert...
Failed to install 'com-appliedrec-plugins-veridcredentials': CordovaError: Uh oh!
"/Users/bs228/Desktop/ionicdev/ionic/plugins/com-appliedrec-plugins-veridcredentials/VerIDModels" not found!
```
so I manually copy the 'VerIDModels' folder from `Ver-ID-Credentials-Cordova-Plugin/verid` to `Ver-ID-Credentials-Cordova-Plugin` folder 
then run again `cordova plugin add <path to the plugin>` and this time the plugin install successfully.
But the problem here when I run `ionic cordova build android` am getting the error below

```
/platforms/android/src/com/appliedrec/plugin/VerIDPlugin.java:137: error: local variable jsonUsers is accessed from within inner class; needs to be declared final
                                        callbackContext.success(jsonUsers);
                                                                ^
/platforms/android/src/com/appliedrec/plugin/VerIDPlugin.java:145: error: local variable e is accessed from within inner class; needs to be declared final
                                        callbackContext.error(e.getLocalizedMessage());
                                                              ^
/platforms/android/src/com/appliedrec/plugin/VerIDPlugin.java:176: error: local variable e is accessed from within inner class; needs to be declared final
                                            callbackContext.error(e.getLocalizedMessage());
```

so its seem like variable needs to be declared final, I added missing `final` keyword to file `/platforms/android/src/com/appliedrec/plugin/VerIDPlugin.java`
after modify  `ionic cordova build android` success.

===============
After running the cordova project, when I load Ver-ID as 

```
var apiSecret = "api secret"; 
verid.load(apiSecret).then(function(){
    console.log('Ver-ID loaded successfully');
}).catch(function(error){
    console.log('Ver-ID failed to load',error);
});
```
Ver-ID load failed with `Ver-ID failed to load Class not found`

================================

Cordova project platform: ionic framework
ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0, browser 5.0.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61

Environment:

   ANDROID_HOME : /Users/bs228/Library/Android/sdk
```
@jakubdolejs,
I would greatly appreciate it if you kindly give me some feedback on this
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanidkpc, thanks for reporting the issues. 
- The path to the models folder has been fixed in b233d4aca87309fa0ff76faf7d951f6c12147b55.
- The variables not being declared are fixed in 6556204027abb040a6690ea58b7268da5f98e532.
We will look into the Class not found error but it didn't come up in our testing. One thing comes to mind: Is it possible that you're using Multidex and the plugin classes are being compiled in a separate dex?

**Comment by sanidkpc** [comment]
Hi @jakubdolejs, Thank you so much for your feedback, really appreciate it.
I can confirm I'm not using Multidex in our cordova app. Also checked build.gradle, no multidex support defined.
still getting the 'Class not found' error. I'm stuck here.
